//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Models.DomainModels;

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IstMvcFrameworkALI17Entities : DbContext
    {
        public IstMvcFrameworkALI17Entities()
            : base("name=IstMvcFrameworkALI17Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<VehicleMaker> VehicleMakers { get; set; }
        public virtual DbSet<VehicleModelMaker> VehicleModelMakers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerVehicle> CustomerVehicles { get; set; }
        public virtual DbSet<OilChangeRecord> OilChangeRecords { get; set; }
        public virtual DbSet<OilMakerCompany> OilMakerCompanies { get; set; }
        public virtual DbSet<OilNetWeight> OilNetWeights { get; set; }
        public virtual DbSet<Oil> Oils { get; set; }
        public virtual DbSet<AirFilter> AirFilters { get; set; }
        public virtual DbSet<BrakeOil> BrakeOils { get; set; }
        public virtual DbSet<OilFilter> OilFilters { get; set; }
        public virtual DbSet<PowerSterringOil> PowerSterringOils { get; set; }
        public virtual DbSet<OilFilterMakerCompany> OilFilterMakerCompanies { get; set; }
    }
}
